-- =========================================
-- SQL SALES ANALYSIS PROJECT
-- =========================================

-- =========================================
-- 1. CUSTOMER TRANSACTION DETAILS
-- =========================================
-- Nazlýcan ÖZSÝMÝTÇÝ isimli kullanýcýnýn yaptýðý iþlemleri tek tabloda görmek

SELECT 
    U.USERNAME_ AS KULLANICIADI,
    U.NAMESURNAME AS ADSOYAD,
    CT.CITY AS IL,
    D.DISTRICT AS SEMT,
    A.ADDRESSTEXT AS ACIKADRES,
    P.DATE_ AS ODEMETARIHI,
    P.APPROVECODE AS BANKAONAYKODU, 
    I.DATE_ AS FATURATARIHI,
    I.CARGOFICHENO AS KARGOFISNO
FROM ORDERS O
INNER JOIN USERS U ON O.USERID = U.ID
INNER JOIN ADDRESS A ON A.ID = O.ADDRESSID
INNER JOIN CITIES CT ON CT.ID = A.CITYID
INNER JOIN DISTRICTS D ON D.ID = A.TOWNID
INNER JOIN PAYMENTS P ON P.ORDERID = O.ID
INNER JOIN INVOICES I ON I.ORDERID = O.ID
WHERE U.NAMESURNAME = 'Nazlýcan ÖZSÝMÝTÇÝ';


-- =========================================
-- 2. ORDER DETAILS WITH PRODUCT INFORMATION
-- =========================================
-- Belirli sipariþin detaylarýný ürün bazýnda görmek

SELECT 
    U.USERNAME_ AS KULLANICIADI,
    U.NAMESURNAME AS ADSOYAD,
    CT.CITY AS IL,
    D.DISTRICT AS SEMT,
    A.ADDRESSTEXT AS ACIKADRES,
    P.DATE_ AS ODEMETARIHI,
    P.APPROVECODE AS BANKAONAYKODU, 
    I.DATE_ AS FATURATARIHI,
    I.CARGOFICHENO AS KARGOFISNO,
    ITM.ITEMCODE AS URUNKODU,
    ITM.ITEMNAME AS URUNADI,
    OD.AMOUNT AS MIKTAR,
    OD.UNITPRICE AS BIRIMFIYAT,
    OD.LINETOTAL AS SATIRTOPLAMI
FROM ORDERS O
INNER JOIN USERS U ON O.USERID = U.ID
INNER JOIN ADDRESS A ON A.ID = O.ADDRESSID
INNER JOIN CITIES CT ON CT.ID = A.CITYID
INNER JOIN DISTRICTS D ON D.ID = A.TOWNID
INNER JOIN PAYMENTS P ON P.ORDERID = O.ID
INNER JOIN INVOICES I ON I.ORDERID = O.ID
INNER JOIN ORDERDETAILS OD ON OD.ORDERID = O.ID
INNER JOIN ITEMS ITM ON ITM.ID = OD.ITEMID
WHERE O.ID = 26121;


-- =========================================
-- 3. CITY-BASED ORDER ANALYSIS
-- =========================================
-- Þehirlere göre toplam sipariþ tutarý, miktarý ve sipariþ sayýsý

SELECT
    CT.CITY AS SEHIRADI,
    SUM(OD.LINETOTAL) AS TOPLAMSIPARIS_TUTARI,
    SUM(OD.AMOUNT) AS TOPLAMSIPARIS_ADEDI,
    COUNT(OD.ID) AS TOPLAMSIPARIS_SAYISI
FROM ORDERS O
INNER JOIN USERS U ON O.USERID = U.ID
INNER JOIN ADDRESS A ON A.ID = O.ADDRESSID
INNER JOIN CITIES CT ON CT.ID = A.CITYID
INNER JOIN DISTRICTS D ON D.ID = A.TOWNID
INNER JOIN PAYMENTS P ON P.ORDERID = O.ID
INNER JOIN INVOICES I ON I.ORDERID = O.ID
INNER JOIN ORDERDETAILS OD ON OD.ORDERID = O.ID
INNER JOIN ITEMS ITM ON ITM.ID = OD.ITEMID
GROUP BY CT.CITY
ORDER BY COUNT(OD.ID) DESC;


-- =========================================
-- 4. CATEGORY-BASED SALES ANALYSIS
-- =========================================
-- Ürün kategorilerine göre sipariþ daðýlýmý

SELECT 
    ITM.CATEGORY1,
    ITM.CATEGORY2,
    ITM.CATEGORY3,
    SUM(OD.LINETOTAL) AS TOPLAMSIPARIS_TUTARI,
    SUM(OD.AMOUNT) AS TOPLAMSIPARIS_ADEDI,
    COUNT(OD.ID) AS TOPLAMSIPARIS_SAYISI,
    SUM(OD.LINETOTAL) / SUM(OD.AMOUNT) AS ORTALAMABIRIMFIYAT
FROM ORDERS O
INNER JOIN USERS U ON O.USERID = U.ID
INNER JOIN ADDRESS A ON A.ID = O.ADDRESSID
INNER JOIN CITIES CT ON CT.ID = A.CITYID
INNER JOIN DISTRICTS D ON D.ID = A.TOWNID
INNER JOIN PAYMENTS P ON P.ORDERID = O.ID
INNER JOIN INVOICES I ON I.ORDERID = O.ID
INNER JOIN ORDERDETAILS OD ON OD.ORDERID = O.ID
INNER JOIN ITEMS ITM ON ITM.ID = OD.ITEMID
GROUP BY ITM.CATEGORY1, ITM.CATEGORY2, ITM.CATEGORY3
ORDER BY ITM.CATEGORY1;


-- =========================================
-- 5. DATE-BASED ORDER ANALYSIS
-- =========================================
-- Tarihe göre sipariþ daðýlýmý

SELECT
    CONVERT(DATE, O.DATE_) AS TARIH,
    SUM(OD.LINETOTAL) AS TOPLAMSIPARIS_TUTAR,
    SUM(OD.AMOUNT) AS TOPLAMSIPARIS_MIKTAR,
    COUNT(OD.ID) AS TOPLAMSIPARIS_SAYISI
FROM ORDERS O
INNER JOIN USERS U ON O.USERID = U.ID
INNER JOIN ADDRESS A ON A.ID = O.ADDRESSID
INNER JOIN CITIES CT ON CT.ID = A.CITYID
INNER JOIN DISTRICTS D ON D.ID = A.TOWNID
INNER JOIN PAYMENTS P ON P.ORDERID = O.ID
INNER JOIN INVOICES I ON I.ORDERID = O.ID
INNER JOIN ORDERDETAILS OD ON OD.ORDERID = O.ID
INNER JOIN ITEMS ITM ON ITM.ID = OD.ITEMID
GROUP BY CONVERT(DATE, O.DATE_)
ORDER BY CONVERT(DATE, O.DATE_);


-- =========================================
-- 6. YEARLY AND MONTHLY ORDER ANALYSIS
-- =========================================
-- Yýllara ve aylara göre sipariþ daðýlýmý

SELECT
    DATEPART(YEAR, O.DATE_) AS YIL,
    DATEPART(MONTH, O.DATE_) AS AY,
    CASE
        WHEN DATEPART(MONTH, O.DATE_) = 1 THEN 'OCAK'
        WHEN DATEPART(MONTH, O.DATE_) = 2 THEN 'ÞUBAT'
        WHEN DATEPART(MONTH, O.DATE_) = 3 THEN 'MART'
        WHEN DATEPART(MONTH, O.DATE_) = 4 THEN 'NÝSAN'
        WHEN DATEPART(MONTH, O.DATE_) = 5 THEN 'MAYIS'
        WHEN DATEPART(MONTH, O.DATE_) = 6 THEN 'HAZÝRAN'
        WHEN DATEPART(MONTH, O.DATE_) = 7 THEN 'TEMMUZ'
        WHEN DATEPART(MONTH, O.DATE_) = 8 THEN 'AÐUSTOS'
        WHEN DATEPART(MONTH, O.DATE_) = 9 THEN 'EYLÜL'
        WHEN DATEPART(MONTH, O.DATE_) = 10 THEN 'EKÝM'
        WHEN DATEPART(MONTH, O.DATE_) = 11 THEN 'KASIM'
        WHEN DATEPART(MONTH, O.DATE_) = 12 THEN 'ARALIK'
    END AS AYADI,
    SUM(OD.LINETOTAL) AS TOPLAMSIPARIS_TUTAR,
    SUM(OD.AMOUNT) AS TOPLAMSIPARIS_MIKTAR,
    COUNT(OD.ID) AS TOPLAMSIPARIS_SAYISI
FROM ORDERS O
INNER JOIN USERS U ON O.USERID = U.ID
INNER JOIN ADDRESS A ON A.ID = O.ADDRESSID
INNER JOIN CITIES CT ON CT.ID = A.CITYID
INNER JOIN DISTRICTS D ON D.ID = A.TOWNID
INNER JOIN PAYMENTS P ON P.ORDERID = O.ID
INNER JOIN INVOICES I ON I.ORDERID = O.ID
INNER JOIN ORDERDETAILS OD ON OD.ORDERID = O.ID
INNER JOIN ITEMS ITM ON ITM.ID = OD.ITEMID
GROUP BY DATEPART(YEAR, O.DATE_), DATEPART(MONTH, O.DATE_)
ORDER BY DATEPART(YEAR, O.DATE_), DATEPART(MONTH, O.DATE_);


-- =========================================
-- 7. PAYMENT TYPE ANALYSIS
-- =========================================
-- Ödeme türüne göre toplam tutar daðýlýmý

SELECT 
    DATEPART(YEAR, DATE_) AS YEAR_,
    DATEPART(MONTH, DATE_) AS AY,
    CASE 
        WHEN PAYMENTTYPE = 1 THEN 'KREDI KARTI'
        WHEN PAYMENTTYPE = 2 THEN 'BANKA HAVALESI'
    END AS ODEMETURU_ACIKLAMA,
    SUM(PAYMENTTOTAL) AS TOPLAMTUTAR
FROM PAYMENTS
GROUP BY DATEPART(YEAR, DATE_), DATEPART(MONTH, DATE_), PAYMENTTYPE
ORDER BY DATEPART(YEAR, DATE_), DATEPART(MONTH, DATE_);


-- =========================================
-- 8. DELIVERY TIME ANALYSIS
-- =========================================
-- Kullanýcý bazýnda ortalama teslimat süresi

SELECT
    U.ID,
    U.NAMESURNAME,
    AVG(DATEDIFF(HOUR, O.DATE_, I.DATE_)) AS ORTALAMA_TESLIMAT_SURESI,
    MIN(DATEDIFF(HOUR, O.DATE_, I.DATE_)) AS ENKISA_TESLIMAT_SURESI,
    MAX(DATEDIFF(HOUR, O.DATE_, I.DATE_)) AS ENUZUN_TESLIMAT_SURESI,
    SUM(O.TOTALPRICE) AS TOPLAM_SIPARIS_TUTARI,
    COUNT(O.ID) AS SIPARISSAYISI
FROM ORDERS O
INNER JOIN USERS U ON O.USERID = U.ID
INNER JOIN ADDRESS A ON A.ID = O.ADDRESSID
INNER JOIN CITIES CT ON CT.ID = A.CITYID
INNER JOIN DISTRICTS D ON D.ID = A.TOWNID
INNER JOIN PAYMENTS P ON P.ORDERID = O.ID
INNER JOIN INVOICES I ON I.ORDERID = O.ID
INNER JOIN ORDERDETAILS OD ON OD.ORDERID = O.ID
INNER JOIN ITEMS ITM ON ITM.ID = OD.ITEMID
GROUP BY U.ID, U.NAMESURNAME
ORDER BY TOPLAM_SIPARIS_TUTARI DESC;